# Generated by Django 6.0.3 on 2026-04-10 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCotReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('forex', 'Forex Major Pairs'), ('metals', 'Precious Metals'), ('crypto', 'Cryptocurrencies')], db_index=True, max_length=20)),
                ('report_date', models.DateField(db_index=True)),
                ('url', models.URLField(max_length=512, unique=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', '-report_date'],
                'indexes': [models.Index(fields=['category', 'year'], name='Historical__categor_aa4759_idx'), models.Index(fields=['year', '-report_date'], name='Historical__year_f069fb_idx')],
                'unique_together': {('category', 'report_date')},
            },
        ),
    ]
