# Generated by Django 6.0.3 on 2026-04-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historical_Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcotreport',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
