# Generated by Django 6.0.3 on 2026-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtrapolatedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('currencies', 'Major Currencies'), ('metals', 'Metals'), ('crypto', 'Cryptocurrency')], max_length=20)),
                ('report_date', models.DateField()),
                ('url', models.URLField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_date', 'category'],
                'unique_together': {('category', 'report_date')},
            },
        ),
    ]
