# Generated by Django 6.0.3 on 2026-04-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handle_Raw_COT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCotReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EURO FX', 'Euro FX  (EUR/USD)'), ('BRITISH POUND', 'British Pound  (GBP/USD)'), ('JAPANESE YEN', 'Japanese Yen  (JPY/USD)'), ('SWISS FRANC', 'Swiss Franc  (CHF/USD)'), ('CANADIAN DOLLAR', 'Canadian Dollar  (CAD/USD)'), ('AUSTRALIAN DOLLAR', 'Australian Dollar  (AUD/USD)'), ('NZ DOLLAR', 'NZ Dollar  (NZD/USD)'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BITCOIN', 'Bitcoin')], db_index=True, max_length=64)),
                ('code', models.CharField(blank=True, help_text='CFTC instrument code, e.g. 099741', max_length=20)),
                ('asset_class', models.CharField(blank=True, choices=[('forex', 'Forex'), ('metal', 'Metal'), ('crypto', 'Crypto')], db_index=True, max_length=10)),
                ('contract_spec', models.CharField(blank=True, help_text='e.g. CONTRACTS OF EUR 125,000', max_length=128)),
                ('as_of_date', models.DateField(db_index=True, help_text='CFTC report date (Tuesday of the reporting week)')),
                ('prev_date', models.DateField(blank=True, help_text='Prior week date used for change calculations', null=True)),
                ('source_file', models.CharField(blank=True, help_text='Original filename, e.g. deacmesf.htm', max_length=128)),
                ('open_interest', models.BigIntegerField(default=0)),
                ('oi_change', models.BigIntegerField(default=0, help_text='Change in open interest from prior week (signed)')),
                ('nc_long', models.BigIntegerField(default=0)),
                ('nc_short', models.BigIntegerField(default=0)),
                ('nc_spreads', models.BigIntegerField(default=0)),
                ('comm_long', models.BigIntegerField(default=0)),
                ('comm_short', models.BigIntegerField(default=0)),
                ('total_long', models.BigIntegerField(default=0)),
                ('total_short', models.BigIntegerField(default=0)),
                ('nr_long', models.BigIntegerField(default=0)),
                ('nr_short', models.BigIntegerField(default=0)),
                ('chg_nc_long', models.BigIntegerField(default=0)),
                ('chg_nc_short', models.BigIntegerField(default=0)),
                ('chg_nc_spreads', models.BigIntegerField(default=0)),
                ('chg_comm_long', models.BigIntegerField(default=0)),
                ('chg_comm_short', models.BigIntegerField(default=0)),
                ('chg_total_long', models.BigIntegerField(default=0)),
                ('chg_total_short', models.BigIntegerField(default=0)),
                ('chg_nr_long', models.BigIntegerField(default=0)),
                ('chg_nr_short', models.BigIntegerField(default=0)),
                ('pct_nc_long', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pct_nc_short', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pct_nc_spreads', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pct_comm_long', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pct_comm_short', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pct_total_long', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pct_total_short', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pct_nr_long', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pct_nr_short', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('traders_total', models.PositiveIntegerField(default=0)),
                ('trd_nc_long', models.PositiveIntegerField(default=0)),
                ('trd_nc_short', models.PositiveIntegerField(default=0)),
                ('trd_nc_spreads', models.PositiveIntegerField(default=0)),
                ('trd_comm_long', models.PositiveIntegerField(default=0)),
                ('trd_comm_short', models.PositiveIntegerField(default=0)),
                ('trd_total_long', models.PositiveIntegerField(default=0)),
                ('trd_total_short', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_log', models.ForeignKey(blank=True, help_text='The scraping session that created/updated this row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_reports', to='Handle_Raw_COT.importlog')),
            ],
            options={
                'verbose_name': 'Scraped COT Report',
                'verbose_name_plural': 'Scraped COT Reports',
                'ordering': ['-as_of_date', 'name'],
                'indexes': [models.Index(fields=['name', 'as_of_date'], name='Handle_Raw__name_76ddcb_idx'), models.Index(fields=['as_of_date'], name='Handle_Raw__as_of_d_e4cf76_idx'), models.Index(fields=['asset_class', 'as_of_date'], name='Handle_Raw__asset_c_831f75_idx'), models.Index(fields=['name', '-as_of_date'], name='Handle_Raw__name_51f52a_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'as_of_date'), name='unique_scraped_instrument_per_week')],
            },
        ),
    ]
